name: Create label

env:
  AZURE_WEBAPP_NAME: app-demo-dke-december-12243707321
  AZURE_REGION: westeurope                                           # Set to your desired Azure region
  DOMAIN_NAME: pocproject0.com        # set domain name of tenant
  DKE_PATH: iac/application/dke       # set path to the folder there DKE files are located

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  enable-co-author:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_SUB_PLATFORM_DKE }}

      - name: Install Required PowerShell Modules
        run: |
          Install-Module -Name ExchangeOnlineManagement -Force -Scope CurrentUser
          Install-Module -Name Az.Accounts -Force -Scope CurrentUser
          Import-Module ExchangeOnlineManagement
          Import-Module Az.Accounts

      - name: Enable Co-Authoring Globally
        run: |
          # Import the authenticated Azure session
          Enable-AzPSSession

          # Extract the tenant ID from the current Azure session
          $tenantId = (Get-AzContext).Tenant.Id

          # Connect to Exchange Online using the current Azure session and tenant ID
          Connect-ExchangeOnline -AzureAuthorizationToken (Get-AzAccessToken -ResourceUrl https://outlook.office365.com).Token -AccountId $tenantId

          # Enable global co-authoring for sensitivity labels
          Set-PolicyConfig -EnableLabelCoauth:$true

          # Disconnect from Exchange Online
          Disconnect-ExchangeOnline -Confirm:$false

  create-label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_SUB_PLATFORM_DKE }}
      
      - name: Create Sensitivity Label
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            #
      - name: Logout
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az logout