name: Create label - simulation

env:
  #AZURE_WEBAPP_NAME: app-demo-dke-december-${{ github.run_id }}    # set this to the name of your Azure Web App including the runID of the GitHub Workflow
  AZURE_WEBAPP_NAME: app-demo-dke-december-12243707321
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  AZURE_WEBAPP_SKU: F1                # Set the SKU used by the app https://azure.microsoft.com/en-us/pricing/details/app-service/windows/#pricing
  AZURE_REGION: westeurope                                           # Set to your desired Azure region
  DOTNET_VERSION: '8.*'                 # set this to the .NET Core version to use
  DOMAIN_NAME: pocproject0.com        # set domain name of tenant
  DKE_PATH: iac/application/dke       # set path to the folder there DKE files are located

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  create-label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_SUB_PLATFORM_DKE }}
      
      - name: Run PowerShell script to create Sensitivity Label
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            pwsh ./iac/application/dke/create-label.ps1 -LabelName "${{ env.AZURE_WEBAPP_NAME }}" -DoubleKeyEncryptionKeyUrl "https://${{ env.AZURE_WEBAPP_NAME }}.${{ env.DOMAIN_NAME  }}/DemoKey1"
      
      - name: Logout
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az logout