name: DKE simple part 2

on:
  workflow_dispatch:
    inputs:
      cname:
        description: "Enter the FQDN (cname) from Part 1"
        required: true
      app_name:
        description: "Enter the app name from Part 1"
        required: true
      rg_name:
        description: "Enter the resource group name from Part 1"
        required: true

jobs:
  configure-dns:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_SUB_PLATFORM_DKE }}

      # Add Custom Domain to Web App
      - name: Add Custom Domain to Web App
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
              az webapp config hostname add \
              --resource-group ${{ github.event.inputs.rg_name }} \
              --webapp-name app-${{ github.event.inputs.app_name }} \
              --hostname ${{ github.event.inputs.cname }}

      # Enable HTTPS for Custom Domain
      - name: Enable HTTPS for Custom Domain
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
              # Enable HTTPS with a managed certificate
              az webapp config ssl bind \
              --resource-group ${{ github.event.inputs.rg_name }} \
              --name app-${{ github.event.inputs.app_name }} \
              --ssl-type SNI \
              --certificate-thumbprint $(az webapp config ssl create \
                  --resource-group ${{ github.event.inputs.rg_name }} \
                  --name app-${{ github.event.inputs.app_name }} \
                  --hostname ${{ github.event.inputs.cname }} \
                  --query "thumbprint" -o tsv)

      - name: Logout
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
              az logout
